name: Compile on Android

on:
  push:
    branches: [ feature/actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-host'
        version: '6.*.*'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$Qt6_DIR >> $GITHUB_ENV
    - name: Install Qt for Android arm64
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-android'
        modules: 'qtlocation qtpositioning'
        target: 'android'
        version: '6.*.*'
        arch: 'android_arm64_v8a'
    - name: Install Qt for Android armv7
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-android'
        modules: 'qtlocation qtpositioning'
        target: 'android'
        version: '6.*.*'
        arch: 'android_armv7'
    - name: Install Qt for Android x86
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-android'
        modules: 'qtlocation qtpositioning'
        target: 'android'
        version: '6.*.*'
        arch: 'android_x86'
    - name: Install Qt for Android x86_64
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-android'
        modules: 'qtlocation qtpositioning'
        target: 'android'
        version: '6.*.*'
        arch: 'android_x86_64'
    - name: Install Additional Software
      run: |
        sudo apt install ninja-build
        echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "platform-tools" "build-tools;33.0.2"
        echo ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.1.8937393 >> $GITHUB_ENV
    - name: Remove Unwanted Software
      run: |
        echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-33-ext4" "platforms;android-33-ext5" "platforms;android-34-ext8"
        echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: android
    - name: Compile and Install
      run: |
        Qt6_DIR_BASE=$(dirname "$Qt6_DIR") ./buildscript-android.sh
    - name: Package
      run: |
        tar cvfz enrouteDependencies_android.tar.gz Qt
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
