name: Compile on iOS

on:
  push:
    branches: [ feature/actions ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-macOS-host'
        version: '6.5.2'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$Qt6_DIR >> $GITHUB_ENV
    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-ios'
        target: 'ios'
        version: '6.5.2'
    - name: Install software
      run: |
        brew install cmake ninja
    - name: Configure and compile zlib
      run: |
        $Qt6_DIR/bin/qt-cmake \
        -G Ninja \
        -S zlib \
        -B build-zlib-iOS \
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
        -DCMAKE_INSTALL_PREFIX=ios
        cmake --build build-zlib-iOS
        cmake --install build-zlib-iOS
    - name: Configure and compile libzip
      run: |
        cmake -E make_directory build
        $Qt6_DIR/bin/qt-cmake \
        -G Ninja  \
        -S libzip \
        -B build-libzip-iOS \
        -DBUILD_DOC=OFF \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_REGRESS=OFF \
        -DBUILD_SHARED_LIBS=OFF \
        -DBUILD_TOOLS=OFF \
        -DENABLE_BZIP2=OFF \
        -DENABLE_LZMA=OFF \
        -DENABLE_ZSTD=OFF \
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
        -DCMAKE_INSTALL_PREFIX=ios
        cmake --build build-libzip-iOS
        cmake --install build-libzip-iOS
    - name: Package
      run: |
        tar cvfz enrouteDependencies_ios.tar.gz ios
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
