name: Compile on iOS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/linux.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/sources.yml"
      - ".github/workflows/windows.yml"

jobs:
  build:

    runs-on: macos-latest
 
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-macOS-host'
        version: '6.8.*'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$Qt6_DIR >> $GITHUB_ENV
    - name: Install Qt for ios
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-ios'
        modules: 'qtlocation qtpositioning'
        target: 'ios'
        version: '6.8.*'
    - name: Install software
      run: |
        brew install ninja
    - name: Compile and Install
      run: |
        Qt6_DIR_BASE=$(dirname "$Qt6_DIR") ./buildscript-ios.sh
    - name: Package
      run: |
        tar cvfz enrouteDependencies_ios.tar.gz Qt
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
