name: Compile on Linux

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/ios.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/sources.yml"
      - ".github/workflows/windows.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        modules: 'qtlocation qtpositioning'
        version: '6.8.*'
    - name: Install Additional Software
      run: |
        sudo apt install ninja-build
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: linux
    - name: Compile and Install
      run: |
        Qt6_DIR_BASE=$(dirname "$Qt6_DIR") ./buildscript-linux.sh
    - name: Package
      run: |
        tar cvfz enrouteDependencies_linux.tar.gz Qt
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
