name: Sources

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/ios.yml"
      - ".github/workflows/linux.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/windows.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Package Sources
      run: |
        cd maplibre-native-qt; tar cvJf ../maplibre-native-qt.tar.xz --exclude='.git' .
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
