name: Sources

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Package Sources
      run: |
        cd maplibre-native-qt; tar cvJf ../maplibre-native-qt.tar.xz --exclude='.git' .
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds *.tar.XZ
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
