name: Compile on Windows

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: 'true'
        modules: 'qtlocation qtpositioning'
        version: '6.*.*'
    - name: Install Additional Software
      run: |
        sudo apt install ninja-build
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: linux
    - name: Compile and Install
      run: |
        Qt6_DIR_BASE=$(dirname "$Qt6_DIR") ./buildscript-windows.bat
    - name: Package
      run: |
        powershell Compress-Archive Qt enrouteDependencies_windows64.zip
    - name: Upload to developerBuilds
      run: |
        gh release upload --clobber developerBuilds enrouteDependencies_windows64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
